name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v1

      - name: Setup npm cache
        uses: actions/setup-node@v2-beta

      - name: Deploy to now
        run: npx vercel --prod --confirm --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
